import { PrismaClient, Gender, AnimalType } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  const animals = [
    // Puppies
    {
      name: 'Bradie',
      breed: 'German Shepherd',
      gender: Gender.Female,
      type: AnimalType.dog,
      age: '7 months old',
      city: 'Walnut',
      state: 'CA',
      house_trained: 'Yes',
      health: 'Vaccinations up to date, spayed',
      good_with: 'Other dogs, children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759753610/bradie_pnpehz.jpg',
      meet_puppy: `Bradie is a sweet 7-month-old German Shepherd with a playful and loving personality. She's already house-trained and in excellent health, with all vaccinations up to date and spayed. Bradie loves spending time with other dogs and children, making her the perfect addition to a family ready for a loyal and affectionate companion.`,
    },
    {
      name: 'Coop',
      breed: 'Husky',
      gender: Gender.Male,
      type: AnimalType.dog,
      age: '5 months old',
      city: 'Seattle',
      state: 'WA',
      house_trained: 'No',
      health: 'Vaccinations needed',
      good_with: 'Other dogs, pets, and children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759947752/coop_ds0l3r.png',
      meet_puppy: `Coop is an energetic 5-month-old Husky who loves adventure and playtime. Smart and curious, he's already house-trained and up to date on all his vaccinations. Coop enjoys making friends with other dogs, pets, and children, and he's always ready to bring fun and joy to any home lucky enough to welcome him.`,
    },
    {
      name: 'Miso',
      breed: 'Terrier Mix',
      gender: Gender.Male,
      type: AnimalType.dog,
      age: '4 months old',
      city: 'Seattle',
      state: 'WA',
      house_trained: 'No',
      health: 'Vaccinations needed',
      good_with: 'Other dogs, pets, and children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759947886/miso_bei9xk.png',
      meet_puppy: `Miso, a 4-month-old male Young Terrier Mix from Seattle, WA — a playful pup who’s not yet house-trained, still needs vaccinations, but gets along wonderfully with other dogs, pets, and children.`,
    },
    {
      name: 'Rex',
      breed: 'Labrador',
      gender: Gender.Male,
      type: AnimalType.dog,
      age: '11 months old',
      city: 'Chicago',
      state: 'IL',
      house_trained: 'Yes',
      health: 'Vaccinations up to date',
      good_with: 'Other dogs, pets, and children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759948056/rex_jsrznm.png',
      meet_puppy: `Rex is an affectionate 11-month-old Labrador with a big heart and boundless energy. He's up to date on vaccinations and gets along wonderfully with other dogs, pets, and children.`,
    },
    {
      name: 'Dug',
      breed: 'Golden Retriever',
      gender: Gender.Male,
      type: AnimalType.dog,
      age: '4 months old',
      city: 'Philadelphia',
      state: 'PA',
      house_trained: 'No',
      health: 'Vaccinations needed',
      good_with: 'Other dogs, pets, and children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759753537/dug_ldbjto.jpg',
      meet_puppy: `Dug is a lovable 4-month-old Golden Retriever full of puppy energy and curiosity. He gets along wonderfully with other dogs, pets, and children.`,
    },
    {
      name: 'Beanie',
      breed: 'Corgi',
      gender: Gender.Female,
      type: AnimalType.dog,
      age: '3 months old',
      city: 'Austin',
      state: 'TX',
      house_trained: 'No',
      health: 'Vaccinations up to date',
      good_with: 'Other dogs, pets, and children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759753659/beanie_uhz0cq.webp',
      meet_puppy: `Beanie is a spunky 3-month-old Corgi with a big personality packed into a little body. Up to date on vaccinations, she's curious, cuddly, and playful.`,
    },
    {
      name: 'Rosco',
      breed: 'Yorkshire Terrier',
      gender: Gender.Male,
      type: AnimalType.dog,
      age: '5 months old',
      city: 'Los Angeles',
      state: 'CA',
      house_trained: 'No',
      health: 'Vaccinations up to date',
      good_with: 'Other dogs, children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759753555/rosco_tunwqi.jpg',
      meet_puppy: `Rosco is an energetic 5-month-old Yorkshire Terrier with a big personality in a tiny package. He's curious, playful, and eager to learn.`,
    },
    {
      name: 'Olia',
      breed: 'Bernese Mountain Dog',
      gender: Gender.Female,
      type: AnimalType.dog,
      age: '3 months old',
      city: 'Minneapolis',
      state: 'MN',
      house_trained: 'No',
      health: 'Vaccinations up to date',
      good_with: 'Other dogs, pets, and children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759753575/olia_e4upuq.jpg',
      meet_puppy: `Olia is a gentle and fluffy 3-month-old Bernese Mountain Dog full of playful energy and curiosity.`,
    },
    {
      name: 'Cooper',
      breed: 'French Bulldog',
      gender: Gender.Male,
      type: AnimalType.dog,
      age: '2 months old',
      city: 'Phoenix',
      state: 'AZ',
      house_trained: 'No',
      health: 'Vaccinations needed',
      good_with: 'Other dogs, pets, and children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759753594/cooper_kb0ipk.webp',
      meet_puppy: `Cooper is an adorable 2-month-old French Bulldog with a playful spark and a whole lot of charm.`,
    },
    {
      name: 'Bella',
      breed: 'Terrier Mix',
      gender: Gender.Female,
      type: AnimalType.dog,
      age: '6 months old',
      city: 'Boston',
      state: 'MA',
      house_trained: 'No',
      health: 'Vaccinations up to date',
      good_with: 'Other dogs, pets, and children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759753602/bella_xcjygd.jpg',
      meet_puppy: `Bella is a bright and bouncy 6-month-old Terrier Mix with a heart full of love and a tail that never stops wagging.`,
    },
    {
      name: 'Charlie',
      breed: 'Australian Shepherd',
      gender: Gender.Male,
      type: AnimalType.dog,
      age: '4 months old',
      city: 'Portland',
      state: 'OR',
      house_trained: 'No',
      health: 'Vaccinations needed',
      good_with: 'Other dogs, pets, and children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759753620/charlie_qqzz6h.jpg',
      meet_puppy: `Charlie is a smart and spirited 4-month-old Australian Shepherd bursting with curiosity and energy.`,
    },
    {
      name: 'Luna',
      breed: 'Cardigan Mix',
      gender: Gender.Female,
      type: AnimalType.dog,
      age: '5 months old',
      city: 'Las Vegas',
      state: 'NV',
      house_trained: 'Yes',
      health: 'Vaccinations up to date',
      good_with: 'Other dogs, pets, and children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759753546/luna_vb2sdd.jpg',
      meet_puppy: `Luna is a sweet and spunky 5-month-old Cardigan Mix who's as loving as she is playful.`,
    },
      //Dogs
    {
      name: 'Gnocchi',
      breed: 'Australian Sheppard',
      gender: Gender.Male,
      type: AnimalType.dog,
      age: '2 years old',
      city: 'Columbus',
      state: 'OH',
      house_trained: 'Yes',
      health: 'Vaccinations up to date, neutered',
      good_with: 'Other dogs, pets, and children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759948352/sheppard_lxiux3.jpg',
      meet_puppy: `Meet Gnocchi, a 2-year-old male Australian Shepherd from Columbus, OH — a smart and friendly dog who’s house-trained, neutered, vaccinations are up to date, and loves being around other dogs, pets, and children.`,
    },
    {
      name: 'Sprout',
      breed: 'Australian Sheppard',
      gender: Gender.Female,
      type: AnimalType.dog,
      age: '1 year old',
      city: 'Indianapolis',
      state: 'IN',
      house_trained: 'Yes',
      health: 'Vaccinations up to date, spayed',
      good_with: 'Children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759948422/cd9bcea35c01f36e89e93061cfa2556499613cae_l0pqoz.jpg',
      meet_puppy: `Sprout is a 1-year-old female Australian Shepherd from Indianapolis, IN — a sweet, house-trained dog who’s spayed, vaccinations are up to date, and loves spending time with children.`
    },
    {
      name: 'Keba',
      breed: 'Malamute',
      gender: Gender.Male,
      type: AnimalType.dog,
      age: '3 years old',
      city: 'Detroit',
      state: 'MI',
      house_trained: 'Yes',
      health: 'Vaccinations up to date, neutered',
      good_with: 'Other dogs, children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759948493/1f478c7827b1292313dfc320b22113e826b90266_nypbbh.jpg',
      meet_puppy: `Keba is a 3-year-old male Malamute from Detroit, MI — a loyal and well-behaved dog who’s house-trained, neutered, vaccinations are up to date, and enjoys being around other dogs and children.`,
    },
    {
      name: 'Stitches',
      breed: 'Labrador',
      gender: Gender.Female,
      type: AnimalType.dog,
      age: '4 years old',
      city: 'Charlotte',
      state: 'NC',
      house_trained: 'Yes',
      health: 'Vaccinations up to date, spayed',
      good_with: 'Other dogs, pets, and children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759948571/0399de1294291e1ef2e9663add649adb1c55ecb8_hetwnk.jpg',
      meet_puppy: `Stitches is a 4-year-old female Labrador — calm, house-trained, spayed, vaccinations are up to date, and gets along wonderfully with other dogs, pets, and children.`,
    },
    {
      name: 'Edna',
      breed: 'Corgi',
      gender: Gender.Male,
      type: AnimalType.dog,
      age: '2 years old',
      city: 'San Antonio',
      state: 'TX',
      house_trained: 'Yes',
      health: 'Vaccinations up to date, neutered',
      good_with: 'Children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759948660/41cb1043ec3d5315f7eb7d80fa0696a70defbc61_jahk57.jpg',
      meet_puppy: `Edna is a 2-year-old male Corgi — cheerful, house-trained, neutered, vaccinations are up to date, and loves spending time with children.`,
    },
    {
      name: 'Ollie',
      breed: 'Border Collie',
      gender: Gender.Female,
      type: AnimalType.dog,
      age: '6 years old',
      city: 'Baltimore',
      state: 'MD',
      house_trained: 'No',
      health: 'Vaccinations up to date',
      good_with: 'Other dogs, children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759948712/1de56cc0b89b8c1ea70cab48f0562520d81b110a_ojxha4.jpg',
      meet_puppy: `Ollie is a 6-year-old female Border Collie — gentle and intelligent, with vaccinations up to date, still working on house training, and friendly with other dogs and children.`,
    },
    {
      name: 'Bacon',
      breed: 'Shiba',
      gender: Gender.Male,
      type: AnimalType.dog,
      age: '5 years old',
      city: 'Memphis',
      state: 'TN',
      house_trained: 'Yes',
      health: 'Vaccinations up to date, neutered',
      good_with: 'Children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759948801/5b521b72554ad384f7484a9620101bfeda28eb70_yyzdhv.jpg',
      meet_puppy: `Bacon is a 5-year-old male Shiba — confident and loyal, house-trained, neutered, vaccinations are up to date, and enjoys spending time with children.`,
    },
    {
      name: 'Henry',
      breed: 'Labrador',
      gender: Gender.Male,
      type: AnimalType.dog,
      age: '3 years old',
      city: 'Milwaukee',
      state: 'WI',
      house_trained: 'Yes',
      health: 'Vaccinations up to date, neutered',
      good_with: 'Other dogs, pets, and children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759948871/b61527e5d08b3c477b136349c4766f757ca3352f_ho6ree.jpg',
      meet_puppy: `Henry is a 3-year-old male Labrador — friendly and affectionate, house-trained, neutered, vaccinations are up to date, and great with other dogs, pets, and children.`,
    },
    {
      name: 'Rosie',
      breed: 'Labrador',
      gender: Gender.Female,
      type: AnimalType.dog,
      age: '3 year old',
      city: 'Albuquerque',
      state: 'NM',
      house_trained: 'Yes',
      health: 'Vaccinations up to date',
      good_with: 'Other dogs, pets, and children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759948944/17801927cf5a3a9b476d9f0effabd573a2b09ad5_prsub0.jpg',
      meet_puppy: `Rosie is a 3-year-old female Labrador — gentle and loving, house-trained, vaccinations are up to date, and gets along beautifully with other dogs, pets, and children.`,
    },
    {
      name: 'Pickle',
      breed: 'Labrador',
      gender: Gender.Female,
      type: AnimalType.dog,
      age: '2 years old',
      city: 'Las Vegas',
      state: 'NV',
      house_trained: 'Yes',
      health: 'Vaccinations up to date, spayed',
      good_with: 'Children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759949005/6a558a20b21b5a7bb36c808f013999efef7c2fbc_rxrwcw.jpg',
      meet_puppy: `Pickle is a 2-year-old female Labrador — playful and affectionate, house-trained, spayed, vaccinations are up to date, and loves being around children.`,
    },
    {
      name: 'Noodle',
      breed: 'Terrier Mix',
      gender: Gender.Male,
      type: AnimalType.dog,
      age: '2 years old',
      city: 'Las Vegas',
      state: 'NV',
      house_trained: 'Yes',
      health: 'Vaccinations up to date, neutered',
      good_with: 'Children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759949076/7b41bf79e0fb7a0c0d77afe214e5b251832ea5c5_x3ptay.jpg',
      meet_puppy: `Noodle is a 2-year-old male Terrier Mix — lively and friendly, house-trained, neutered, vaccinations are up to date, and enjoys spending time with children.`,
    },
    {
      name: 'Lark',
      breed: 'Jack Russell',
      gender: Gender.Male,
      type: AnimalType.dog,
      age: '2 years old',
      city: 'Las Vegas',
      state: 'NV',
      house_trained: 'Yes',
      health: 'Vaccinations up to date, neutered',
      good_with: 'Children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759949139/3a2b367ff8074562e72696e58874dbd69d6e87ab_ngiscl.jpg',
      meet_puppy: `Lark is a 2-year-old male Jack Russell — energetic and curious, house-trained, neutered, vaccinations are up to date, and loves playing with children.`,
    },
    // Cats
    {
      name: 'Celeste',
      breed: 'Medium Hair',
      gender: Gender.Female,
      type: AnimalType.cat,
      age: '2 years old',
      city: 'New York',
      state: 'NY',
      house_trained: 'Yes',
      health: 'Vaccinations up to date, neutered',
      good_with: 'Other cats, children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759951762/cd2d7fc3a79869b0913dc6f332a249275e380364_vpfgfe.jpg',
      meet_puppy: `Celeste is a 2-year-old female Medium Hair cat — calm and affectionate, house-trained, vaccinations are up to date, neutered, and enjoys the company of other cats and children.`,
    },
    {
      name: 'Tulip',
      breed: 'Medium Hair',
      gender: Gender.Female,
      type: AnimalType.cat,
      age: '1 year old',
      city: 'San Francisco',
      state: 'CA',
      house_trained: 'Yes',
      health: 'Vaccinations up to date, spayed',
      good_with: 'Children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759951756/93c3d7375e4c731bdb0090b956461ab1e0eac91a_tpw0pf.jpg',
      meet_puppy: `Tulip is a 1-year-old female Medium Hair cat — gentle and playful, house-trained, spayed, vaccinations are up to date, and loves spending time with children.`,
    },
    {
      name: 'Morris',
      breed: 'Short Hair',
      gender: Gender.Male,
      type: AnimalType.cat,
      age: '3 years old',
      city: 'Miami',
      state: 'FL',
      house_trained: 'Yes',
      health: 'Vaccinations up to date',
      good_with: 'Other cats',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759951680/1fb70167be168297ac98a78d8d9cd6ea6b3a97fb_lyhzdq.jpg',
      meet_puppy: `Morris is a 3-year-old male Short Hair cat — calm and friendly, house-trained, vaccinations are up to date, and enjoys being around other cats.`,
    },
    {
      name: 'Pippa',
      breed: 'Short Hair',
      gender: Gender.Female,
      type: AnimalType.cat,
      age: '2 years old',
      city: 'Denver',
      state: 'CO',
      house_trained: 'Yes',
      health: 'Vaccinations up to date',
      good_with: 'Other cats, children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759951677/f87c5b2a2182e9176f6d5d6b916c503604d396bb_pl9pak.jpg',
      meet_puppy: `Pippa is a 2-year-old female Short Hair cat — curious and affectionate, house-trained, vaccinations are up to date, and gets along well with other cats and children.`,
    },
    {
      name: 'Maverick',
      breed: 'Short Hair',
      gender: Gender.Male,
      type: AnimalType.cat,
      age: '4 years old',
      city: 'Houston',
      state: 'TX',
      house_trained: 'Yes',
      health: 'Vaccinations up to date, neutered',
      good_with: 'Other cats, pets, and children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759951676/9dc907ae72674a5e98bd471f4be0e1735fa6290c_f7zwrm.jpg',
      meet_puppy: `Maverick is a 4-year-old male Short Hair cat — confident and affectionate, house-trained, neutered, vaccinations are up to date, and gets along wonderfully with other cats, pets, and children.`,
    },
    {
      name: 'Toast',
      breed: 'Medium Hair',
      gender: Gender.Female,
      type: AnimalType.cat,
      age: '2 years old',
      city: 'Atlanta',
      state: 'GA',
      house_trained: 'Yes',
      health: 'Vaccinations up to date, spayed',
      good_with: 'Children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759951674/45bfab50ad5dda277b6cb07a32a5400fa3d0923b_znflnk.jpg',
      meet_puppy: `Toast is a 2-year-old female Medium Hair cat — sweet and gentle, house-trained, spayed, vaccinations are up to date, and loves being around children.`,
    },
    {
      name: 'Autumn',
      breed: 'Short Hair',
      gender: Gender.Male,
      type: AnimalType.cat,
      age: '1 year old',
      city: 'Seattle',
      state: 'WA',
      house_trained: 'Yes',
      health: 'Vaccinations up to date',
      good_with: 'Other cats, pets',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759951672/a9726eea1f7df75b146ff2a2d29a424874c93eee_uehcoq.jpg',
      meet_puppy: `Autumn is a 1-year-old male Short Hair cat — playful and easygoing, house-trained, vaccinations are up to date, and enjoys the company of other cats and pets.`,
    },
    {
      name: 'Liam',
      breed: 'Short Hair',
      gender: Gender.Male,
      type: AnimalType.cat,
      age: '5 years old',
      city: 'San Diego',
      state: 'CA',
      house_trained: 'Yes',
      health: 'Vaccinations up to date, neutered',
      good_with: 'Children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759951671/c71e74a42499739e4d549f89f1898e858177a5d9_trwqjz.jpg',
      meet_puppy: `Liam is a 5-year-old male Short Hair cat — calm and loving, house-trained, neutered, vaccinations are up to date, and enjoys spending time with children.`,
    },
    {
      name: 'Miles',
      breed: 'Short Hair',
      gender: Gender.Male,
      type: AnimalType.cat,
      age: '3 years old',
      city: 'Portland',
      state: 'OR',
      house_trained: 'Yes',
      health: 'Vaccinations up to date, neutered',
      good_with: 'Other cats, pets, and children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759951658/d2abfe2437b1578757b69ccc7f9236cecf5ff534_g9xhun.jpg',
      meet_puppy: `Miles is a 3-year-old male Short Hair cat — friendly and relaxed, house-trained, neutered, vaccinations are up to date, and gets along wonderfully with other cats, pets, and children.`,
    },
    {
      name: 'Banjo',
      breed: 'Medium Hair',
      gender: Gender.Male,
      type: AnimalType.cat,
      age: '2 years old',
      city: 'Dallas',
      state: 'TX',
      house_trained: 'Yes',
      health: 'Vaccinations up to date',
      good_with: 'Children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759951679/4dd97ea74ff10fd56d864ca340600494aae43b63_oikzu5.jpg',
      meet_puppy: `Banjo is a 2-year-old male Medium Hair cat — gentle and affectionate, house-trained, vaccinations are up to date, and loves spending time with children.`,
    },
    {
      name: 'Eclipse',
      breed: 'Medium Hair',
      gender: Gender.Male,
      type: AnimalType.cat,
      age: '3 years old',
      city: 'Dallas',
      state: 'TX',
      house_trained: 'Yes',
      health: 'Vaccinations up to date',
      good_with: 'Children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759951674/8ef40129b336be01b6f0418c3c7d31b7663bccff_p4kqz8.jpg',
      meet_puppy: `Eclipse is a 3-year-old male Medium Hair cat — calm and affectionate, house-trained, vaccinations are up to date, and enjoys spending time with children.`,
    },
    {
      name: 'Penelope',
      breed: 'Long Hair',
      gender: Gender.Female,
      type: AnimalType.cat,
      age: '2 years old',
      city: 'Dallas',
      state: 'TX',
      house_trained: 'Yes',
      health: 'Vaccinations up to date',
      good_with: 'Children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759951649/7d6eab84b77f7c1db075b4b8d7e775562eb21d0d_swgsn6.jpg',
      meet_puppy: `Penelope is a 2-year-old female Long Hair cat — graceful and affectionate, house-trained, vaccinations are up to date, and enjoys spending time with children.`,
    },
      // kittens
    {
      name: 'Daisy',
      breed: 'Medium Hair',
      gender: Gender.Female,
      type: AnimalType.cat,
      age: '2 months old',
      city: 'New York',
      state: 'NY',
      house_trained: 'Yes',
      health: 'Vaccinations up to date, neutered',
      good_with: 'Other cats, children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759952859/02b76213cf5f555ef9c4ef74e1a5b7810662c1ad_k2ijgh.png',
      meet_puppy: `Daisy is a 2-month-old female Medium Hair kitten — playful and curious, house-trained, neutered, vaccinations are up to date, and loves being around other cats and children.`,
    },
    {
      name: 'Zoey',
      breed: 'Short Hair',
      gender: Gender.Female,
      type: AnimalType.cat,
      age: '3 months old',
      city: 'San Francisco',
      state: 'CA',
      house_trained: 'Yes',
      health: 'Vaccinations up to date, spayed',
      good_with: 'Children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759952860/0ba4e7123402429c1e03399dc05737e87423e3e3_naflov.png',
      meet_puppy: `Zoey is a 1-year-old female Short Hair cat — friendly and playful, house-trained, spayed, vaccinations are up to date, and enjoys spending time with children.`,
    },
    {
      name: 'Peanut',
      breed: 'Short Hair',
      gender: Gender.Male,
      type: AnimalType.cat,
      age: '3 months old',
      city: 'Miami',
      state: 'FL',
      house_trained: 'Yes',
      health: 'Vaccinations up to date',
      good_with: 'Other cats',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759952856/ac0a26f749932fc22e0bbbd1fa8e6eca9ac68ba8_scssz4.png',
      meet_puppy: `Peanut is a 3-month-old male Short Hair kitten — curious and playful, house-trained, vaccinations are up to date, and gets along well with other cats.`,
    },
    {
      name: 'Penny',
      breed: 'Short Hair',
      gender: Gender.Female,
      type: AnimalType.cat,
      age: '2 months old',
      city: 'Denver',
      state: 'CO',
      house_trained: 'Yes',
      health: 'Vaccinations up to date',
      good_with: 'Other cats, children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759952855/653736be1c643fad05b1909c6a923450fe99fc4e_itlagp.png',
      meet_puppy: `Penny is a 2-month-old female Short Hair kitten — playful and sweet, house-trained, vaccinations are up to date, and loves being around other cats and children.`,
    },
    {
      name: 'Leo',
      breed: 'Medium Hair',
      gender: Gender.Male,
      type: AnimalType.cat,
      age: '4 months old',
      city: 'Houston',
      state: 'TX',
      house_trained: 'Yes',
      health: 'Vaccinations up to date, neutered',
      good_with: 'Other cats, pets, and children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759952853/d42b8af3e07e5549b3fa763553ba54afbf09fa67_u3aquk.png',
      meet_puppy: `Leo is a 4-year-old male Medium Hair cat — calm and affectionate, house-trained, neutered, vaccinations are up to date, and gets along wonderfully with other cats, pets, and children.`,
    },
    {
      name: 'Kumo',
      breed: 'Medium Hair',
      gender: Gender.Female,
      type: AnimalType.cat,
      age: '2 months old',
      city: 'Atlanta',
      state: 'GA',
      house_trained: 'Yes',
      health: 'Vaccinations up to date, spayed',
      good_with: 'Children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759952851/c7b92db76c0340bc8c55204296831b23a2ecc20e_uxcrn3.png',
      meet_puppy: `Kumo is a 2-month-old female Medium Hair kitten — playful and gentle, house-trained, spayed, vaccinations are up to date, and loves spending time with children.`,
    },
    {
      name: 'Callie',
      breed: 'Medium Hair',
      gender: Gender.Male,
      type: AnimalType.cat,
      age: '5 months old',
      city: 'Seattle',
      state: 'WA',
      house_trained: 'Yes',
      health: 'Vaccinations up to date',
      good_with: 'Other cats, pets',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759952850/5f0ccd621ab09dc922e16615a11cb4702313570f_w6xh0v.png',
      meet_puppy: `Callie is a 5-month-old male Medium Hair kitten — curious and affectionate, house-trained, vaccinations are up to date, and enjoys the company of other cats and pets.`,
    },
    {
      name: 'Suki',
      breed: 'Short Hair',
      gender: Gender.Male,
      type: AnimalType.cat,
      age: '5 months old',
      city: 'San Diego',
      state: 'CA',
      house_trained: 'Yes',
      health: 'Vaccinations up to date, neutered',
      good_with: 'Children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759952848/29f8986ab5c58900d8fc515e64a831e096f40de7_prr0wm.png',
      meet_puppy: `Suki is a 5-month-old male Short Hair kitten — playful and affectionate, house-trained, neutered, vaccinations are up to date, and loves spending time with children.`,
    },
    {
      name: 'Lily',
      breed: 'Short Hair',
      gender: Gender.Male,
      type: AnimalType.cat,
      age: '3 months old',
      city: 'Portland',
      state: 'OR',
      house_trained: 'Yes',
      health: 'Vaccinations up to date, neutered',
      good_with: 'Other cats, pets, and children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759959433/edgar-nKC772R_qog-unsplash_flzv99.jpg',
      meet_puppy: `Lily is a 3-month-old male Short Hair kitten — lively and affectionate, house-trained, neutered, vaccinations are up to date, and gets along wonderfully with other cats, pets, and children.`,
    },
    {
      name: 'Oreo',
      breed: 'Medium Hair',
      gender: Gender.Male,
      type: AnimalType.cat,
      age: '6 months old',
      city: 'Dallas',
      state: 'TX',
      house_trained: 'Yes',
      health: 'Vaccinations up to date',
      good_with: 'Children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759953598/e6dcd5cadf3cb8c1c50a18f4d7d96b4d6965886b_binni0.png',
      meet_puppy: `Oreo is a 6-month-old male Medium Hair kitten — playful and gentle, house-trained, vaccinations are up to date, and enjoys spending time with children.`,
    },
    {
      name: 'Oliver',
      breed: 'Medium Hair',
      gender: Gender.Male,
      type: AnimalType.cat,
      age: '3 months old',
      city: 'Dallas',
      state: 'TX',
      house_trained: 'Yes',
      health: 'Vaccinations up to date',
      good_with: 'Children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759952844/7af2da34d66117aa10efaab58bb0db752c05cb4b_lesk0f.png',
      meet_puppy: `Oliver is a 3-month-old male Medium Hair kitten — curious and sweet, house-trained, vaccinations are up to date, and loves being around children.`,
    },
    {
      name: 'Luna',
      breed: 'Long Hair',
      gender: Gender.Female,
      type: AnimalType.cat,
      age: '2 months old',
      city: 'Dallas',
      state: 'TX',
      house_trained: 'Yes',
      health: 'Vaccinations up to date',
      good_with: 'Children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759952860/ebeb63934913ffe4080bef22325e19d5805addfc_fhilka.png',
      meet_puppy: `Luna is a 2-month-old female Long Hair kitten — gentle and playful, house-trained, vaccinations are up to date, and enjoys spending time with children.`,
    },
    // Other animals
    {
      name: 'Thumper',
      breed: 'Holland Lop Rabbit',
      gender: Gender.Male,
      type: AnimalType.other,
      age: '1 year old',
      city: 'Sacramento',
      state: 'CA',
      house_trained: 'No',
      health: 'Healthy, neutered',
      good_with: 'Other pets, children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759953808/rabbit_g5ka2i.jpg',
      meet_puppy: `Thumper is an adorable Holland Lop rabbit with floppy ears and a gentle nature.`,
    },
    {
      name: 'Squeaky',
      breed: 'Guinea Pig',
      gender: Gender.Female,
      type: AnimalType.other,
      age: '6 months old',
      city: 'Orlando',
      state: 'FL',
      house_trained: 'No',
      health: 'Healthy',
      good_with: 'Other pets, children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759953807/pig_vsfh17.jpg',
      meet_puppy: `Squeaky is a cheerful guinea pig who loves fresh vegetables and gentle cuddles.`,
    },
    {
      name: 'Nibbles',
      breed: 'Hamster',
      gender: Gender.Male,
      type: AnimalType.other,
      age: '4 months old',
      city: 'Raleigh',
      state: 'NC',
      house_trained: 'No',
      health: 'Healthy',
      good_with: 'Children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759953891/hamster_rkdmb7.jpg',
      meet_puppy: `Nibbles is a tiny hamster with a big personality who loves running on his wheel.`,
    },
    {
      name: 'Polly',
      breed: 'Parakeet',
      gender: Gender.Female,
      type: AnimalType.other,
      age: '2 years old',
      city: 'Nashville',
      state: 'TN',
      house_trained: 'No',
      health: 'Healthy',
      good_with: 'Other pets',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759953891/parakeet_phkscv.jpg',
      meet_puppy: `Polly is a colorful parakeet who loves to chirp and play with toys.`,
    },
    {
      name: 'Shelly',
      breed: 'Turtle',
      gender: Gender.Female,
      type: AnimalType.other,
      age: '3 years old',
      city: 'Tampa',
      state: 'FL',
      house_trained: 'No',
      health: 'Healthy',
      good_with: 'Other pets',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759941974/turtle_x8t8ji.jpg',
      meet_puppy: `Shelly is a calm turtle who enjoys basking under her heat lamp and munching greens.`,
    },
  ]

  await prisma.vaccination.deleteMany()
  await prisma.animal.deleteMany()

  const createdAnimals = await Promise.all(
    animals.map((animal) => prisma.animal.create({ data: animal }))
  )

  const vaccinations = [
    {
      vaccine_name: 'Rabies',
      vaccination_date: new Date('2024-01-15'),
      expiration_date: new Date('2027-01-15'),
      batch_number: 'RAB-2024-001',
      animal_id: createdAnimals[0].id, // Bradie
    },
    {
      vaccine_name: 'DHPP',
      vaccination_date: new Date('2024-02-10'),
      expiration_date: new Date('2025-02-10'),
      batch_number: 'DHPP-2024-045',
      animal_id: createdAnimals[0].id, // Bradie
    },
    {
      vaccine_name: 'Bordetella',
      vaccination_date: new Date('2024-03-01'),
      expiration_date: new Date('2025-03-01'),
      batch_number: 'BOR-2024-112',
      animal_id: createdAnimals[3].id, // Rex
    },
    {
      vaccine_name: 'Rabies',
      vaccination_date: new Date('2024-01-20'),
      expiration_date: new Date('2027-01-20'),
      batch_number: 'RAB-2024-002',
      animal_id: createdAnimals[11].id, // Luna
    },
    {
      vaccine_name: 'DHPP',
      vaccination_date: new Date('2024-02-15'),
      expiration_date: new Date('2025-02-15'),
      batch_number: 'DHPP-2024-050',
      animal_id: createdAnimals[11].id, // Luna
    },
  ]

  await prisma.vaccination.createMany({ data: vaccinations })

  console.log('Database seeded with animal and vaccination data')
}

main()
  .then(() => prisma.$disconnect())
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
