import { PrismaClient, Gender } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  const puppies = [
    {
      name: 'Bradie',
      breed: 'German Shepherd',
      gender: Gender.Female,
      age: '7 months old',
      city: 'Walnut',
      state: 'CA',
      house_trained: 'Yes',
      health: 'Vaccinations up to date, spayed',
      good_with: 'Other dogs, children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759753610/bradie_pnpehz.jpg',
      meet_puppy: `Bradie is a sweet 7-month-old German Shepherd with a playful and loving personality. She’s already house-trained and in excellent health, with all vaccinations up to date and spayed. Bradie loves spending time with other dogs and children, making her the perfect addition to a family ready for a loyal and affectionate companion.`,
    },
    {
      name: 'Coop',
      breed: 'Husky',
      gender: Gender.Male,
      age: '5 months old',
      city: 'Seattle',
      state: 'WA',
      house_trained: 'No',
      health: 'Vaccinations needed',
      good_with: 'Other dogs, pets, and children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759753628/coop_cmevn3.jpg',
      meet_puppy: `Coop is an energetic 5-month-old Husky who loves adventure and playtime. Smart and curious, he’s already house-trained and up to date on all his vaccinations. Coop enjoys making friends with other dogs, pets, and children, and he’s always ready to bring fun and joy to any home lucky enough to welcome him.`,
    },
    {
      name: 'Maya',
      breed: 'Pitbull',
      gender: Gender.Female,
      age: '10 months old',
      city: 'San Jose',
      state: 'CA',
      house_trained: 'No',
      health: 'Vaccinations up to date',
      good_with: 'Children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759753566/maya_vcixep.jpg',
      meet_puppy: `Maya is an adorable 10-month-old Pitbull with a playful spirit and a heart full of love. This sweet girl is still working on house-training but is up to date on all her vaccinations and ready to find her forever family.`,
    },
    {
      name: 'Rex',
      breed: 'Labrador',
      gender: Gender.Male,
      age: '11 months old',
      city: 'Chicago',
      state: 'IL',
      house_trained: 'Yes',
      health: 'Vaccinations up to date',
      good_with: 'Other dogs, pets, and children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759753584/rex_bft1sz.jpg',
      meet_puppy: `Rex is an affectionate 11-month-old Labrador with a big heart and boundless energy. He’s up to date on vaccinations and gets along wonderfully with other dogs, pets, and children.`,
    },
    {
      name: 'Dug',
      breed: 'Golden Retriever',
      gender: Gender.Male,
      age: '4 months old',
      city: 'Philadelphia',
      state: 'PA',
      house_trained: 'No',
      health: 'Vaccinations needed',
      good_with: 'Other dogs, pets, and children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759753537/dug_ldbjto.jpg',
      meet_puppy: `Dug is a lovable 4-month-old Golden Retriever full of puppy energy and curiosity. He gets along wonderfully with other dogs, pets, and children.`,
    },
    {
      name: 'Beanie',
      breed: 'Corgi',
      gender: Gender.Female,
      age: '3 months old',
      city: 'Austin',
      state: 'TX',
      house_trained: 'No',
      health: 'Vaccinations up to date',
      good_with: 'Other dogs, pets, and children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759753659/beanie_uhz0cq.webp',
      meet_puppy: `Beanie is a spunky 3-month-old Corgi with a big personality packed into a little body. Up to date on vaccinations, she’s curious, cuddly, and playful.`,
    },
    {
      name: 'Rosco',
      breed: 'Yorkshire Terrier',
      gender: Gender.Male,
      age: '5 months old',
      city: 'Los Angeles',
      state: 'CA',
      house_trained: 'No',
      health: 'Vaccinations up to date',
      good_with: 'Other dogs, children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759753555/rosco_tunwqi.jpg',
      meet_puppy: `Rosco is an energetic 5-month-old Yorkshire Terrier with a big personality in a tiny package. He’s curious, playful, and eager to learn.`,
    },
    {
      name: 'Olia',
      breed: 'Bernese Mountain Dog',
      gender: Gender.Female,
      age: '3 months old',
      city: 'Minneapolis',
      state: 'MN',
      house_trained: 'No',
      health: 'Vaccinations up to date',
      good_with: 'Other dogs, pets, and children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759753575/olia_e4upuq.jpg',
      meet_puppy: `Olia is a gentle and fluffy 3-month-old Bernese Mountain Dog full of playful energy and curiosity.`,
    },
    {
      name: 'Cooper',
      breed: 'French Bulldog',
      gender: Gender.Male,
      age: '2 months old',
      city: 'Phoenix',
      state: 'AZ',
      house_trained: 'No',
      health: 'Vaccinations needed',
      good_with: 'Other dogs, pets, and children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759753594/cooper_kb0ipk.webp',
      meet_puppy: `Cooper is an adorable 2-month-old French Bulldog with a playful spark and a whole lot of charm.`,
    },
    {
      name: 'Bella',
      breed: 'Terrier Mix',
      gender: Gender.Female,
      age: '6 months old',
      city: 'Boston',
      state: 'MA',
      house_trained: 'No',
      health: 'Vaccinations up to date',
      good_with: 'Other dogs, pets, and children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759753602/bella_xcjygd.jpg',
      meet_puppy: `Bella is a bright and bouncy 6-month-old Terrier Mix with a heart full of love and a tail that never stops wagging.`,
    },
    {
      name: 'Charlie',
      breed: 'Australian Shepherd',
      gender: Gender.Male,
      age: '4 months old',
      city: 'Portland',
      state: 'OR',
      house_trained: 'No',
      health: 'Vaccinations needed',
      good_with: 'Other dogs, pets, and children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759753620/charlie_qqzz6h.jpg',
      meet_puppy: `Charlie is a smart and spirited 4-month-old Australian Shepherd bursting with curiosity and energy.`,
    },
    {
      name: 'Luna',
      breed: 'Cardigan Mix',
      gender: Gender.Female,
      age: '5 months old',
      city: 'Las Vegas',
      state: 'NV',
      house_trained: 'Yes',
      health: 'Vaccinations up to date',
      good_with: 'Other dogs, pets, and children',
      image: 'https://res.cloudinary.com/dqv1wpjqz/image/upload/v1759753546/luna_vb2sdd.jpg',
      meet_puppy: `Luna is a sweet and spunky 5-month-old Cardigan Mix who’s as loving as she is playful.`,
    },
  ]

  await prisma.animal.deleteMany()
  await prisma.animal.createMany({ data: puppies })

  console.log('Database seeded with animal data')
}

main()
  .then(() => prisma.$disconnect())
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
